
spring:
  application:
    name: DouyinSearchService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douyintest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: onetest


server:
  port: 9009
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka