

spring:
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: itcast
    password: 123321
    virtual-host: /douyin # 虚拟主机
  application:
    name: DouyinIntroduceService
  redis:
    host: localhost  # Redis服务器地址
    port: 6379       # Redis端口号

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

server:
  port: 8585
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka